version: "3.5"

services:
  front-end:
    container_name: front-end
    build:
      context: .
      dockerfile: ./front-end/Dockerfile
    volumes:
      - "./front-end:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "4200:4200"
      - "80:8888"
      - "49153:49153"
    env_file:
      - "./front-end/.env"
    environment:
      - NODE_ENV=development
  nginx:
      build: ./nginx
      volumes:
          - .:/usr/src/app
      depends_on:
          - front-end
      ports:
          - "81:81"